#!sh

# installer/uninstaller for dotfiles

options=("install all" "uninstall all" "install individual package" "uninstall individual package")

choice=$(printf '%s\n' "${options[@]}" | fzf)
echo "chose: ${choice}"

case $choice in
    "install all")
        stow --verbose=1 --target="${HOME}" $(fd --type=directory --strip-cwd-prefix)
        ;;

    "uninstall all")
        stow --delete --verbose=1 --target="${HOME}" $(fd --type=directory --strip-cwd-prefix)
        ;;

    "install individual package")
        package=$(fd --type=directory --strip-cwd-prefix | fzf)
        stow --verbose=1 --target="${HOME}" "${package}"
        ;;

    "uninstall individual package")
        package=$(fd --type=directory --strip-cwd-prefix | fzf)
        stow --delete --verbose=1 --target="${HOME}" "${package}"
        ;;

esac
