# add hints for all normal mode actions
set -add global autoinfo normal

# user commands
map global user d -docstring "fuzzy-find files" ':+ kcr-fzf-files<ret>' 
map global user b -docstring "fuzzy-find buffers" ':+ kcr-fzf-buffers<ret>'
map global user v -docstring "open kakrc" ':e ~/.config/kak/kakrc<ret>'
map global user f -docstring "format current buffer" ':format<ret>'
map global user a -docstring "open selection in broswer" '<a-|>xargs $BROWSER<ret>'
map global user s -docstring "search repo" ':+ kcr-fzf-grep<ret>'
map global user g -docstring "open lazygit " ':+ lazygit<ret>'

# disable window title
set global ui_options ncurses_set_title=false

source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "robertmeta/plug.kak" noload

plug "abstractlyZach/nord.kak" %{
    colorscheme nord
}
# cosmetics
# add relative line numbers
add-highlighter global/ number-lines -relative -hlcursor -min-digits 2

plug "alexherbo2/auto-pairs.kak" %{
    require-module auto-pairs
    auto-pairs-enable 
}

# highlight current line
plug "insipx/kak-crosshairs" %{
    cursorline
    # nord2, can't set this in the colorscheme because it's plugin-specific
    set-face global crosshairs_line default,rgb:434c5e
}

hook global ModuleLoaded x11 %{
    alias global popup x11-terminal
}

plug "andreyorst/powerline.kak" defer powerline %{
    #Configure powerline.kak as desired
    powerline-theme solarized-dark-termcolors
    powerline-separator triangle
} config %{
    powerline-start
}

plug "kak-lsp/kak-lsp" do %{
    cargo install --locked --force --path .
} config %{

    # uncomment to enable debugging
    # eval %sh{echo ${kak_opt_lsp_cmd} >> /tmp/kak-lsp.log}
    # set global lsp_cmd "kak-lsp -s %val{session} -vvv --log /tmp/kak-lsp.log"

    hook global WinSetOption filetype=(python) %{
        # set-option window lsp_auto_highlight_references true
        # set-option window lsp_hover_anchor false
        lsp-auto-hover-enable
        echo -debug "Enabling LSP for filetype %opt{filetype}"
        lsp-enable-window
    }
    hook global WinSetOption filetype=(typescript|javascript) %{
        # set-option window lsp_auto_highlight_references true
        # set-option window lsp_hover_anchor false
        lsp-auto-hover-enable
        echo -debug "Enabling LSP for filetype %opt{filetype}"
        lsp-enable-window
    }
}

hook global WinSetOption filetype=python %{
    # hook window BufWritePre .* lsp-formatting-sync
    # use black to format
    set-option window formatcmd "poetry run black -q -"
}

plug "andreyorst/smarttab.kak" defer smarttab %{
    # when `backspace' is pressed, 4 spaces are deleted at once
    set-option global softtabstop 4
} config %{
    # these languages will use `expandtab' behavior
    hook global WinSetOption filetype=.* expandtab
    # these languages will use `noexpandtab' behavior
    #hook global WinSetOption filetype=(makefile|gas) noexpandtab
    # these languages will use `smarttab' behavior
    #hook global WinSetOption filetype=(c|cpp) smarttab
}

plug "alexherbo2/toggle-highlighter.kak" %{
    require-module toggle-highlighter
    map global user w -docstring "toggle whitespace highlighter" ':toggle-highlighter window/ show-whitespaces<ret>'
}

