#!/bin/bash

# colors are in AARRGGBB format. "A" is for transparency

# global settings
yabai -m config mouse_follows_focus          off
# yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               on
yabai -m config window_shadow                off
yabai -m config window_border                on
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xffebcb8b
yabai -m config normal_window_border_color   0x9fb48ead
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  30
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   7

# specific space settings
# yabai -m config --space 7 layout             float

# window rules
yabai -m rule --add app="Microsoft Outlook" space=2
yabai -m rule --add app=Slack space=3
yabai -m rule --add app=Spotify space=1
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Google Chrome$" manage=off

# signals
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

echo "yabai configuration loaded.."
