#!/usr/bin/env sh

# change directory anywhere
function cdd() {
    target_dir=$(
	fd --type d --color=always --absolute-path . "$HOME" --exclude "Library" |
            cat - <(echo "$HOME/.config") | 
	    sed "s,$HOME,~," |
	    fzf |
	    sed "s,~,$HOME,"
    ) 
    [[ -z $target_dir ]] || cd $target_dir
}

# search everything!
se() {
    fd --type f --color=always . "$HOME" "$HOME/.config" | 
	fzf | 
	xargs -r $EDITOR
}

# fuzzy extension finder
# search all files that end with a certain extension
fx() {
    # test for empty 
    [[ -z "$1" ]] && echo "Fuzzy extension finder: need to specify an extension" && return 1 
    fd --extension "$1" --color=always --absolute-path . "$HOME" |
	fzf |
	xargs --no-run-if-empty $EDITOR
}

timezsh() {
  shell=${1-$SHELL}
  for i in $(seq 1 10); do time $shell -i -c exit; done
}
