# Modifications needed:
# * if you use a different terminal emulator than alacritty, replace all instances of
#       "alacritty" in this file with whatever you use
# * if you use a different shell, replace all instances of "zsh" with whatever you use
# * make sure you have the required dependencies installed (see README.md)
[root]
sizes = [50, 50]
children = ["left", "right"]
split = "horizontal"

[left]
# show the tree of ~ with max depth 2
command = "alacritty -e zsh -c 'fd --max-depth 2; zsh'"

[right]
sizes = [50, 50]
children = ["neofetch", "ls"]
split = "vertical"

[neofetch]
# run neofetch to show off your sick operating system. I use arch btw.
command = "alacritty -e zsh -c 'neofetch; zsh'"

[ls]
# ls all files in long-format inside ~
command = "alacritty -e zsh -c 'ls --all -l --color=always; zsh'"
